### ISSUE TITLE
Pip3 requirements is missing

### ISSUE THREAD

**Issue by Hentai-Nat** [Pedro4064/Anime-NAS#1]
I cannot find the requirements.txt in the files you provided.

**Comment by Pedro4064** [comment]
Sorry for the trouble. I'm working on it right away.

**Comment by Pedro4064** [comment]
Added the requirements.txt file.

By the Way we are trying to port the whole application to Docker and we already have a stable release out, so if you wish to give the docker version a try you can check it out at the `Docker_Develop` branch (it is much easier to install).

[Docker version](https://github.com/Pedro4064/Anime-NAS/tree/Docker_Develop)
